"""add_product_price_to_abtest

Revision ID: 5d4dff151a89
Revises: 2096e374bca5
Create Date: 2025-08-24 07:17:38.938564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4dff151a89'
down_revision = '2096e374bca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_tests', sa.Column('product_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ab_tests', 'product_price')
    # ### end Alembic commands ###
