"""Initial A/B test tables with complete schema

Revision ID: 97033cde847a
Revises: 
Create Date: 2025-08-19 05:41:21.827297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97033cde847a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('baseline_image_url', sa.String(length=500), nullable=True),
    sa.Column('challenger_image_url', sa.String(length=500), nullable=True),
    sa.Column('ai_winner_variant_id', sa.Integer(), nullable=True),
    sa.Column('user_selected_winner_id', sa.Integer(), nullable=True),
    sa.Column('winner_selection_deadline', sa.DateTime(), nullable=True),
    sa.Column('test_cycle_number', sa.Integer(), nullable=True),
    sa.Column('parent_test_id', sa.Integer(), nullable=True),
    sa.Column('test_duration_days', sa.Integer(), nullable=True),
    sa.Column('traffic_split_ratio', sa.Float(), nullable=True),
    sa.Column('min_sample_size', sa.Integer(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('guardrail_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_tests_id'), 'ab_tests', ['id'], unique=False)
    op.create_index(op.f('ix_ab_tests_name'), 'ab_tests', ['name'], unique=False)
    op.create_index(op.f('ix_ab_tests_product_id'), 'ab_tests', ['product_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_status'), 'ab_tests', ['status'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ab_test_id', sa.Integer(), nullable=False),
    sa.Column('variant_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('purchases', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Float(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_content_hash'), 'variants', ['content_hash'], unique=False)
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    op.create_index(op.f('ix_variants_is_active'), 'variants', ['is_active'], unique=False)
    op.create_table('performance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ab_test_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('interaction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_logs_id'), 'performance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_performance_logs_interaction_type'), 'performance_logs', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_performance_logs_session_id'), 'performance_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_timestamp'), 'performance_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_performance_logs_user_id'), 'performance_logs', ['user_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ab_test_id', sa.Integer(), nullable=False),
    sa.Column('winner_variant_id', sa.Integer(), nullable=True),
    sa.Column('winner_score', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('total_impressions', sa.Integer(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_purchases', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ),
    sa.ForeignKeyConstraint(['winner_variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_performance_logs_user_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_timestamp'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_session_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_interaction_type'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_id'), table_name='performance_logs')
    op.drop_table('performance_logs')
    op.drop_index(op.f('ix_variants_is_active'), table_name='variants')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_content_hash'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_ab_tests_status'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_product_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_name'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_id'), table_name='ab_tests')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
