"""add_cart_purchases_field

Revision ID: ae2643286510
Revises: 5d4dff151a89
Create Date: 2025-08-24 07:42:59.158389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2643286510'
down_revision = '5d4dff151a89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('total_cart_purchases', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('cart_purchases', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'cart_purchases')
    op.drop_column('test_results', 'total_cart_purchases')
    # ### end Alembic commands ###
